# Generated by Django 4.1.4 on 2022-12-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер класса')),
                ('title', models.CharField(max_length=1, verbose_name='Класс')),
                ('curator', models.CharField(max_length=25, verbose_name='Классная руководительница')),
            ],
        ),
    ]
