# Generated by Django 4.1.4 on 2022-12-09 07:42

from django.db import migrations, models
import student.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('klass', models.PositiveIntegerField(validators=[student.utils.validate_klas], verbose_name='Класс')),
                ('phone_parent', models.CharField(help_text='Номер должен содержать междкнародный формат', max_length=55, unique=True, validators=[student.utils.validate_phone_number], verbose_name='Номер Родителей')),
                ('live', models.CharField(max_length=255, verbose_name='Место проживания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изоброжение')),
            ],
        ),
    ]
