# Generated by Django 4.1.4 on 2022-12-09 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_alter_teachers_options_alter_teachers_sur_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lessons', models.CharField(max_length=55, verbose_name='Название урока')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers', verbose_name='Учитель')),
            ],
        ),
    ]
